Set-StrictMode -Version Latest

$script:EffortOrder = @('none', 'minimal', 'low', 'medium', 'high', 'xhigh', 'max')

. (Join-Path $PSScriptRoot 'ModelRouter.Core.ps1')
. (Join-Path $PSScriptRoot 'ModelRouter.State.ps1')
. (Join-Path $PSScriptRoot 'ModelRouter.Invoke.ps1')

Export-ModuleMember -Function @(
    'Get-ModelRouterHubRoot',
    'Get-ModelRouterLadder',
    'Get-ModelRouterCandidatePolicy',
    'Get-ModelRouterAgentRegistry',
    'Resolve-ModelRouterRankToken',
    'Resolve-ModelRouterAllowedRanks',
    'Resolve-ModelRouterRankKey',
    'Get-ModelRouterRankSpec',
    'Get-ModelRouterConfig',
    'Get-OpenRouterCatalog',
    'Get-OpenRouterModelRecord',
    'Get-ModelRouterIntent',
    'Get-RequestedEffort',
    'Get-ModelRouterReasoningMetadata',
    'Resolve-ModelRouterEffort',
    'Select-ModelRouterModel',
    'Get-ModelRouterFallbacks',
    'Measure-ModelRouterInput',
    'Get-DefaultOutputCap',
    'Get-EffectiveModelPricing',
    'Get-ModelRouterCostEstimate',
    'Get-ModelRouterAgentProfile',
    'Resolve-GlobalModelRoute',
    'Resolve-ModelRoute',
    'Get-ModelRouterRuntimeRoot',
    'Get-ModelRouterHealthPath',
    'Get-SafeModelRouterSessionId',
    'Get-ModelRouterHealthState',
    'Get-ModelRouterModelHealth',
    'Write-ModelRouterHealthEvent',
    'Write-ModelRouterKeyHealthEvent',
    'Enter-ModelRouterCircuit',
    'Exit-ModelRouterCircuitProbe',
    'Get-ModelRouterSession',
    'Save-ModelRouterSession',
    'Reserve-ModelRouterBudget',
    'Complete-ModelRouterBudgetReservation',
    'Undo-ModelRouterBudgetReservation',
    'Get-ModelRouterCalibrationMultiplier',
    'Update-ModelRouterCalibration',
    'Get-ModelRouterVerifiedR3Models',
    'Ensure-ModelRouterR3Allowlist',
    'Set-ModelRouterR3Verification',
    'Get-OpenRouterKey',
    'Get-OpenRouterKeyInfo',
    'Get-ModelRouterHttpStatusCode',
    'Get-ModelRouterErrorCategory',
    'Get-ModelRouterUsageDetails',
    'New-ModelRouterRequestBody',
    'Get-ModelRouterDynamicR3Candidates',
    'Invoke-ModelRouterChat'
)
